##
## EPITECH PROJECT, 2020
## CNA_groundhog_2019 [WSL: Ubuntu]
## File description:
## Makefile
##

NAME	=	groundhog

SRC		=	test.py

all:
	cp $(SRC) $(NAME)
	chmod +x $(NAME)

clean:

fclean: clean
	@rm -f $(NAME)

re: fclean all