/*
** EPITECH PROJECT, 2020
** PSU_strace_2019 [WSL: Ubuntu]
** File description:
** strace
*/

#include "ftrace.h"

const syscall_t syscall_tab[333] = {
    { "read", LONG, (int[]){INT, STRING, SIZE_T, NONE} },
    { "write", LONG, (int[]){INT, STRING, SIZE_T, NONE} },
    { "open", INT, (int[]){STRING, INT, NONE} },
    { "close", INT, (int[]){INT, NONE} },
    { "stat", INT, (int[]){STRING, POINTER, NONE} },
    { "fstat", INT, (int[]){INT, POINTER, NONE} },
    { "lstat", INT, (int[]){STRING, POINTER, NONE} },
    { "poll", INT, (int[]){POINTER, SIZE_T, INT, NONE} },
    { "lseek", LONG, (int[]){INT, LONG, INT, NONE} },
    { "mmap", POINTER, (int[]){POINTER, SIZE_T, INT, INT, INT, LONG, NONE} },
    { "mprotect", INT, (int[]){POINTER, SIZE_T, INT, NONE} },
    { "munmap", INT, (int[]){POINTER, SIZE_T, NONE} },
    { "brk", POINTER, (int[]){POINTER, NONE} },
    { "rt_sigaction", INT, (int[]){INT, POINTER, POINTER, NONE} },
    { "rt_sigprocmask", INT, (int[]){INT, POINTER, POINTER, SIZE_T, NONE} },
    { "rt_sigreturn", INT, (int[]){SIZE_T, NONE} },
    { "ioctl", INT, (int[]){INT, SIZE_T, POINTER, NONE} },
    { "pread64", SIZE_T, (int[]){INT, POINTER, SIZE_T, LONG, NONE} },
    { "pwrite64", SIZE_T, (int[]){INT, POINTER, SIZE_T, LONG, NONE} },
    { "readv", LONG, (int[]){INT, POINTER, INT, NONE} },
    { "writev", LONG, (int[]){INT, POINTER, INT, NONE} },
    { "access", INT, (int[]){STRING, INT, NONE} },
    { "pipe", INT, (int[]){POINTER, NONE} },
    { "select", INT, (int[]){INT, POINTER, POINTER, POINTER, POINTER, NONE} },
    { "sched_yield", INT, (int[]){NONE} },
    { "mremap", POINTER,
        (int[]){POINTER, SIZE_T, SIZE_T, INT, POINTER, NONE} },
    { "msync", INT, (int[]){POINTER, SIZE_T, INT, NONE} },
    { "mincore", INT, (int[]){POINTER, SIZE_T, STRING, NONE} },
    { "madvise", INT, (int[]){POINTER, SIZE_T, INT, NONE} },
    { "shmget", INT, (int[]){INT, SIZE_T, INT, NONE} },
    { "shmat", POINTER, (int[]){INT, POINTER, INT, NONE} },
    { "shmctl", INT, (int[]){INT, INT, POINTER, NONE} },
    { "dup", INT, (int[]){INT, NONE} },
    { "dup2", INT, (int[]){INT, INT, NONE} },
    { "pause", INT, (int[]){NONE} },
    { "nanosleep", INT, (int[]){POINTER, POINTER, NONE} },
    { "getitimer", INT, (int[]){INT, POINTER, NONE} },
    { "alarm", INT, (int[]){UNSIGNED, NONE} },
    { "setitimer", INT, (int[]){INT, POINTER, POINTER, NONE} },
    { "getpid", INT, (int[]){NONE} },
    { "sendfile", LONG, (int[]){INT, INT, POINTER, SIZE_T, NONE} },
    { "socket", INT, (int[]){INT, INT, INT, NONE} },
    { "connect", INT, (int[]){INT, POINTER, UNSIGNED, NONE} },
    { "accept", INT, (int[]){INT, POINTER, POINTER, NONE} },
    { "sendto", LONG,
        (int[]){INT, POINTER, SIZE_T, INT, POINTER, UNSIGNED, NONE} },
    { "recvfrom", LONG,
        (int[]){INT, POINTER, SIZE_T, INT, POINTER, POINTER, NONE} },
    { "sendmsg", LONG, (int[]){INT, POINTER, INT, NONE} },
    { "recvmsg", LONG, (int[]){INT, POINTER, INT, NONE} },
    { "shutdown", INT, (int[]){INT, INT, NONE} },
    { "bind", INT, (int[]){INT, POINTER, UNSIGNED, NONE} },
    { "listen", INT, (int[]){INT, INT, NONE} },
    { "getsockname", INT, (int[]){INT, POINTER, POINTER, NONE} },
    { "getpeername", INT, (int[]){INT, POINTER, POINTER, NONE} },
    { "socketpair", INT, (int[]){INT, INT, INT, POINTER, NONE} },
    { "setsockopt", INT, (int[]){INT, INT, INT, POINTER, UNSIGNED, NONE} },
    { "getsockopt", INT, (int[]){INT, INT, INT, POINTER, POINTER, NONE} },
    { "clone", INT, (int[]){POINTER, POINTER, INT, POINTER, NONE} },
    { "fork", INT, (int[]){NONE} },
    { "vfork", INT, (int[]){NONE} },
    { "execve", INT, (int[]){STRING, POINTER, POINTER, NONE} },
    { "exit", NONE, (int[]){NONE} },
    { "wait4", INT, (int[]){INT, POINTER, INT, POINTER, NONE} },
    { "kill", INT, (int[]){INT, INT, NONE} },
    { "uname", INT, (int[]){POINTER, NONE} },
    { "semget", INT, (int[]){INT, INT, INT, NONE} },
    { "semop", INT, (int[]){INT, POINTER, SIZE_T, NONE} },
    { "semctl", INT, (int[]){INT, INT, INT, POINTER, NONE} },
    { "shmdt", INT, (int[]){POINTER, NONE} },
    { "msgget", INT, (int[]){INT, INT, NONE} },
    { "msgsnd", INT, (int[]){INT, POINTER, SIZE_T, INT, NONE} },
    { "msgrcv", LONG, (int[]){INT, POINTER, SIZE_T, LONG, INT, NONE} },
    { "msgctl", INT, (int[]){INT, INT, POINTER, NONE} },
    { "fcntl", INT, (int[]){INT, INT, POINTER, NONE} },
    { "flock", INT, (int[]){INT, INT, NONE} },
    { "fsync", INT, (int[]){INT, NONE} },
    { "fdatasync", INT, (int[]){INT, NONE} },
    { "truncate", INT, (int[]){STRING, LONG, NONE} },
    { "ftruncate", INT, (int[]){INT, LONG, NONE} },
    { "getdents", INT, (int[]){UNSIGNED, POINTER, UNSIGNED, NONE} },
    { "getcwd", STRING, (int[]){STRING, SIZE_T, NONE} },
    { "chdir", INT, (int[]){STRING, NONE} },
    { "fchdir", INT, (int[]){INT, NONE} },
    { "rename", INT, (int[]){STRING, STRING, NONE} },
    { "mkdir", INT, (int[]){STRING, UNSIGNED, NONE} },
    { "rmdir", INT, (int[]){STRING, NONE} },
    { "creat", INT, (int[]){STRING, UNSIGNED, NONE} },
    { "link", INT, (int[]){STRING, STRING, NONE} },
    { "unlink", INT, (int[]){STRING, NONE} },
    { "symlink", INT, (int[]){STRING, STRING, NONE} },
    { "readlink", LONG, (int[]){STRING, STRING, SIZE_T, NONE} },
    { "chmod", INT, (int[]){STRING, UNSIGNED, NONE} },
    { "fchmod", INT, (int[]){INT, UNSIGNED, NONE} },
    { "chown", INT, (int[]){STRING, UNSIGNED, UNSIGNED, NONE} },
    { "fchown", INT, (int[]){INT, UNSIGNED, UNSIGNED, NONE} },
    { "lchown", INT, (int[]){STRING, UNSIGNED, UNSIGNED, NONE} },
    { "umask", UNSIGNED, (int[]){UNSIGNED, NONE} },
    { "gettimeofday", INT, (int[]){POINTER, POINTER, NONE} },
    { "getrlimit", INT, (int[]){INT, POINTER, NONE} },
    { "getrusage", INT, (int[]){INT, POINTER, NONE} },
    { "sysinfo", INT, (int[]){POINTER, NONE} },
    { "times", LONG, (int[]){POINTER, NONE} },
    { "ptrace", LONG, (int[]){INT, INT, POINTER, POINTER, NONE} },
    { "getuid", UNSIGNED, (int[]){NONE} },
    { "syslog", INT, (int[]){INT, STRING, INT, NONE} },
    { "getgid", UNSIGNED, (int[]){NONE} },
    { "setuid", INT, (int[]){UNSIGNED, NONE} },
    { "setgid", INT, (int[]){UNSIGNED, NONE} },
    { "geteuid", UNSIGNED, (int[]){NONE} },
    { "getegid", UNSIGNED, (int[]){NONE} },
    { "setpgid", INT, (int[]){INT, INT, NONE} },
    { "getppid", INT, (int[]){NONE} },
    { "getpgrp", INT, (int[]){NONE} },
    { "setsid", INT, (int[]){NONE} },
    { "setreuid", INT, (int[]){UNSIGNED, UNSIGNED, NONE} },
    { "setregid", INT, (int[]){UNSIGNED, UNSIGNED, NONE} },
    { "getgroups", INT, (int[]){INT, POINTER, NONE} },
    { "setgroups", INT, (int[]){SIZE_T, POINTER, NONE} },
    { "setresuid", INT, (int[]){UNSIGNED, UNSIGNED, UNSIGNED, NONE} },
    { "getresuid", INT, (int[]){POINTER, POINTER, POINTER, NONE} },
    { "setresgid", INT, (int[]){UNSIGNED, UNSIGNED, UNSIGNED, NONE} },
    { "getresgid", INT, (int[]){POINTER, POINTER, POINTER, NONE} },
    { "getpgid", INT, (int[]){INT, NONE} },
    { "setfsuid", INT, (int[]){UNSIGNED, NONE} },
    { "setfsgid", INT, (int[]){UNSIGNED, NONE} },
    { "getsid", INT, (int[]){INT, NONE} },
    { "capget", INT, (int[]){POINTER, POINTER, NONE} },
    { "capset", INT, (int[]){POINTER, POINTER, NONE} },
    { "rt_sigpending", NONE, (int[]){NONE} },
    { "rt_sigtimedwait", NONE, (int[]){NONE} },
    { "rt_sigqueueinfo", INT, (int[]){INT, INT, POINTER, NONE} },
    { "rt_sigsuspend", NONE, (int[]){NONE} },
    { "sigaltstack", INT, (int[]){POINTER, POINTER, NONE} },
    { "utime", INT, (int[]){STRING, POINTER, NONE} },
    { "mknod", INT, (int[]){STRING, UNSIGNED, SIZE_T, NONE} },
    { "uselib", INT, (int[]){STRING, NONE} },
    { "personality", INT, (int[]){SIZE_T, NONE} },
    { "ustat", INT, (int[]){SIZE_T, POINTER, NONE} },
    { "statfs", INT, (int[]){STRING, POINTER, NONE} },
    { "fstatfs", INT, (int[]){INT, POINTER, NONE} },
    { "sysfs", INT, (int[]){INT, STRING, NONE} },
    { "getpriority", INT, (int[]){INT, UNSIGNED, NONE} },
    { "setpriority", INT, (int[]){INT, UNSIGNED, INT, NONE} },
    { "sched_setparam", INT, (int[]){INT, POINTER, NONE} },
    { "sched_getparam", INT, (int[]){INT, POINTER, NONE} },
    { "sched_setscheduler", INT, (int[]){INT, INT, POINTER, NONE} },
    { "sched_getscheduler", INT, (int[]){INT, NONE} },
    { "sched_get_priority_max", INT, (int[]){INT, NONE} },
    { "sched_get_priority_min", INT, (int[]){INT, NONE} },
    { "sched_rr_get_interval", INT, (int[]){INT, POINTER, NONE} },
    { "mlock", INT, (int[]){POINTER, SIZE_T, NONE} },
    { "munlock", INT, (int[]){POINTER, SIZE_T, NONE} },
    { "mlockall", INT, (int[]){INT, NONE} },
    { "munlockall", INT, (int[]){NONE} },
    { "vhangup", INT, (int[]){NONE} },
    { "modify_ldt", INT, (int[]){INT, POINTER, SIZE_T, NONE} },
    { "pivot_root", INT, (int[]){STRING, STRING, NONE} },
    { "_sysctl", INT, (int[]){POINTER, NONE} },
    { "prctl", INT, (int[]){INT, SIZE_T, SIZE_T, SIZE_T, SIZE_T, NONE} },
    { "arch_prctl", INT, (int[]){INT, SIZE_T, NONE} },
    { "adjtimex", INT, (int[]){POINTER, NONE} },
    { "setrlimit", INT, (int[]){INT, POINTER, NONE} },
    { "chroot", INT, (int[]){STRING, NONE} },
    { "sync", NONE, (int[]){NONE} },
    { "acct", INT, (int[]){STRING, NONE} },
    { "settimeofday", INT, (int[]){POINTER, POINTER, NONE} },
    { "mount", INT, (int[]){STRING, STRING, STRING, SIZE_T, POINTER, NONE} },
    { "umount2", INT, (int[]){STRING, INT, NONE} },
    { "swapon", INT, (int[]){STRING, INT, NONE} },
    { "swapoff", INT, (int[]){STRING, NONE} },
    { "reboot", INT, (int[]){INT, INT, INT, POINTER, NONE} },
    { "sethostname", INT, (int[]){STRING, SIZE_T, NONE} },
    { "setdomainname", INT, (int[]){STRING, SIZE_T, NONE} },
    { "iopl", INT, (int[]){INT, NONE} },
    { "ioperm", INT, (int[]){SIZE_T, SIZE_T, INT, NONE} },
    { "create_module", STRING, (int[]){STRING, SIZE_T, NONE} },
    { "init_module", INT, (int[]){POINTER, SIZE_T, STRING, NONE} },
    { "delete_module", INT, (int[]){STRING, INT, NONE} },
    { "get_kernel_syms", INT, (int[]){POINTER, NONE} },
    { "query_module", INT,
        (int[]){STRING, INT, POINTER, SIZE_T, POINTER, NONE} },
    { "quotactl", INT, (int[]){INT, STRING, INT, STRING, NONE} },
    { "nfsservctl", LONG, (int[]){INT, POINTER, POINTER, NONE} },
    { "getpmsg", NONE, (int[]){NONE} },
    { "putpmsg", NONE, (int[]){NONE} },
    { "afs_syscall", NONE, (int[]){NONE} },
    { "tuxcall", NONE, (int[]){NONE} },
    { "security", NONE, (int[]){NONE} },
    { "gettid", INT, (int[]){NONE} },
    { "readahead", LONG, (int[]){INT, INT, SIZE_T, NONE} },
    { "setxattr", NONE, (int[]){NONE} },
    { "lsetxattr", NONE, (int[]){NONE} },
    { "fsetxattr", NONE, (int[]){NONE} },
    { "getxattr", NONE, (int[]){NONE} },
    { "lgetxattr", NONE, (int[]){NONE} },
    { "fgetxattr", NONE, (int[]){NONE} },
    { "listxattr", NONE, (int[]){NONE} },
    { "llistxattr", NONE, (int[]){NONE} },
    { "flistxattr", NONE, (int[]){NONE} },
    { "removexattr", NONE, (int[]){NONE} },
    { "lremovexattr", NONE, (int[]){NONE} },
    { "fremovexattr", NONE, (int[]){NONE} },
    { "tkill", INT, (int[]){INT, INT, NONE} },
    { "time", LONG, (int[]){POINTER, NONE} },
    { "futex", INT, (int[]){POINTER, INT, INT, POINTER, POINTER, INT, NONE} },
    { "sched_setaffinity", INT, (int[]){INT, SIZE_T, POINTER, NONE} },
    { "sched_getaffinity", INT, (int[]){INT, SIZE_T, POINTER, NONE} },
    { "set_thread_area", INT, (int[]){POINTER, NONE} },
    { "io_setup", INT, (int[]){UNSIGNED, POINTER, NONE} },
    { "io_destroy", INT, (int[]){POINTER, NONE} },
    { "io_getevents", INT,
        (int[]){POINTER, LONG, LONG, POINTER, POINTER, NONE} },
    { "io_submit", INT, (int[]){POINTER, LONG, POINTER, NONE} },
    { "io_cancel", INT, (int[]){POINTER, POINTER, POINTER, NONE} },
    { "get_thread_area", INT, (int[]){POINTER, NONE} },
    { "lookup_dcookie", INT, (int[]){SIZE_T, STRING, SIZE_T, NONE} },
    { "epoll_create", INT, (int[]){INT, NONE} },
    { "epoll_ctl_old", NONE, (int[]){NONE} },
    { "epoll_wait_old", NONE, (int[]){NONE} },
    { "remap_file_pages", INT,
        (int[]){POINTER, SIZE_T, INT, SIZE_T, INT, NONE} },
    { "getdents64", INT, (int[]){UNSIGNED, POINTER, UNSIGNED, NONE} },
    { "set_tid_address", LONG, (int[]){POINTER, NONE} },
    { "restart_syscall", INT, (int[]){NONE} },
    { "semtimedop", INT, (int[]){INT, POINTER, SIZE_T, POINTER, NONE} },
    { "fadvise64", NONE, (int[]){NONE} },
    { "timer_create", INT, (int[]){INT, POINTER, POINTER, NONE} },
    { "timer_settime", INT, (int[]){POINTER, INT, POINTER, POINTER, NONE} },
    { "timer_gettime", INT, (int[]){POINTER, POINTER, NONE} },
    { "timer_getoverrun", INT, (int[]){POINTER, NONE} },
    { "timer_delete", INT, (int[]){POINTER, NONE} },
    { "clock_settime", INT, (int[]){INT, POINTER, NONE} },
    { "clock_gettime", INT, (int[]){INT, POINTER, NONE} },
    { "clock_getres", INT, (int[]){INT, POINTER, NONE} },
    { "clock_nanosleep", INT, (int[]){INT, INT, POINTER, POINTER, NONE} },
    { "exit_group", NONE, (int[]){INT, NONE} },
    { "epoll_wait", INT, (int[]){INT, POINTER, INT, INT, NONE} },
    { "epoll_ctl", INT, (int[]){INT, INT, INT, POINTER, NONE} },
    { "tgkill", INT, (int[]){INT, INT, INT, NONE} },
    { "utimes", INT, (int[]){STRING, POINTER, NONE} },
    { "vserver", NONE, (int[]){NONE} },
    { "mbind", LONG,
        (int[]){POINTER, SIZE_T, INT, POINTER, SIZE_T, UNSIGNED, NONE} },
    { "set_mempolicy", LONG, (int[]){INT, POINTER, SIZE_T, NONE} },
    { "get_mempolicy", LONG,
        (int[]){POINTER, POINTER, SIZE_T, POINTER, SIZE_T, NONE} },
    { "mq_open", INT, (int[]){STRING, INT, NONE} },
    { "mq_unlink", INT, (int[]){STRING, NONE} },
    { "mq_timedsend", INT,
        (int[]){INT, STRING, SIZE_T, UNSIGNED, POINTER, NONE} },
    { "mq_timedreceive", LONG,
        (int[]){INT, STRING, SIZE_T, POINTER, POINTER, NONE} },
    { "mq_notify", INT, (int[]){INT, POINTER, NONE} },
    { "mq_getsetattr", INT, (int[]){INT, POINTER, POINTER, NONE} },
    { "kexec_load", LONG, (int[]){SIZE_T, SIZE_T, POINTER, SIZE_T, NONE} },
    { "waitid", INT, (int[]){INT, UNSIGNED, POINTER, INT, NONE} },
    { "add_key", POINTER,
        (int[]){STRING, STRING, POINTER, SIZE_T, POINTER, NONE} },
    { "request_key", POINTER,
        (int[]){STRING, STRING, STRING, POINTER, NONE} },
    { "keyctl", NONE, (int[]){NONE} },
    { "ioprio_set", INT, (int[]){INT, INT, INT, NONE} },
    { "ioprio_get", INT, (int[]){INT, INT, NONE} },
    { "inotify_init", INT, (int[]){NONE} },
    { "inotify_add_watch", INT, (int[]){INT, STRING, UNSIGNED, NONE} },
    { "inotify_rm_watch", INT, (int[]){INT, INT, NONE} },
    { "migrate_pages", LONG, (int[]){INT, SIZE_T, POINTER, POINTER, NONE} },
    { "openat", INT, (int[]){INT, STRING, INT, NONE} },
    { "mkdirat", INT, (int[]){INT, STRING, UNSIGNED, NONE} },
    { "mknodat", INT, (int[]){INT, STRING, UNSIGNED, SIZE_T, NONE} },
    { "fchownat", INT, (int[]){INT, STRING, UNSIGNED, UNSIGNED, INT, NONE} },
    { "futimesat", INT, (int[]){INT, STRING, POINTER, NONE} },
    { "newfstatat", NONE, (int[]){NONE} },
    { "unlinkat", INT, (int[]){INT, STRING, INT, NONE} },
    { "renameat", INT, (int[]){INT, STRING, INT, STRING, NONE} },
    { "linkat", INT, (int[]){INT, STRING, INT, STRING, INT, NONE} },
    { "symlinkat", INT, (int[]){STRING, INT, STRING, NONE} },
    { "readlinkat", LONG, (int[]){INT, STRING, STRING, SIZE_T, NONE} },
    { "fchmodat", INT, (int[]){INT, STRING, UNSIGNED, INT, NONE} },
    { "faccessat", INT, (int[]){INT, STRING, INT, INT, NONE} },
    { "pselect6", NONE, (int[]){NONE} },
    { "ppoll", INT, (int[]){POINTER, SIZE_T, POINTER, POINTER, NONE} },
    { "unshare", INT, (int[]){INT, NONE} },
    { "set_robust_list", LONG, (int[]){POINTER, SIZE_T, NONE} },
    { "get_robust_list", LONG, (int[]){INT, POINTER, POINTER, NONE} },
    { "splice", LONG,
        (int[]){INT, POINTER, INT, POINTER, SIZE_T, UNSIGNED, NONE} },
    { "tee", LONG, (int[]){INT, INT, SIZE_T, UNSIGNED, NONE} },
    { "sync_file_range", INT, (int[]){INT, LONG, LONG, UNSIGNED, NONE} },
    { "vmsplice", LONG, (int[]){INT, POINTER, SIZE_T, UNSIGNED, NONE} },
    { "move_pages", LONG,
        (int[]){INT, SIZE_T, POINTER, POINTER, POINTER, INT, NONE} },
    { "utimensat", INT, (int[]){INT, STRING, POINTER, INT, NONE} },
    { "epoll_pwait", INT, (int[]){INT, POINTER, INT, INT, POINTER, NONE} },
    { "signalfd", INT, (int[]){INT, POINTER, INT, NONE} },
    { "timerfd_create", INT, (int[]){INT, INT, NONE} },
    { "eventfd", INT, (int[]){UNSIGNED, INT, NONE} },
    { "fallocate", INT, (int[]){INT, INT, LONG, LONG, NONE} },
    { "timerfd_settime", INT, (int[]){INT, INT, POINTER, POINTER, NONE} },
    { "timerfd_gettime", INT, (int[]){INT, POINTER, NONE} },
    { "accept4", INT, (int[]){INT, POINTER, POINTER, INT, NONE} },
    { "signalfd4", NONE, (int[]){NONE} },
    { "eventfd2", NONE, (int[]){NONE} },
    { "epoll_create1", INT, (int[]){INT, NONE} },
    { "dup3", INT, (int[]){INT, INT, INT, NONE} },
    { "pipe2", INT, (int[]){POINTER, INT, NONE} },
    { "inotify_init1", INT, (int[]){INT, NONE} },
    { "preadv", LONG, (int[]){INT, POINTER, INT, LONG, NONE} },
    { "pwritev", LONG, (int[]){INT, POINTER, INT, LONG, NONE} },
    { "rt_tgsigqueueinfo", INT, (int[]){INT, INT, INT, POINTER, NONE} },
    { "perf_event_open", INT, (int[]){POINTER, INT, INT, INT, SIZE_T, NONE} },
    { "recvmmsg", INT, (int[]){INT, POINTER, UNSIGNED, INT, POINTER, NONE} },
    { "fanotify_init", INT, (int[]){UNSIGNED, UNSIGNED, NONE} },
    { "fanotify_mark", INT,
        (int[]){INT, UNSIGNED, SIZE_T, INT, STRING, NONE} },
    { "prlimit64", INT, (int[]){INT, INT, POINTER, POINTER, NONE} },
    { "name_to_handle_at", INT,
        (int[]){INT, STRING, POINTER, POINTER, INT, NONE} },
    { "open_by_handle_at", INT, (int[]){INT, POINTER, INT, NONE} },
    { "clock_adjtime", NONE, (int[]){NONE} },
    { "syncfs", INT, (int[]){INT, NONE} },
    { "sendmmsg", INT, (int[]){INT, POINTER, UNSIGNED, INT, NONE} },
    { "setns", INT, (int[]){INT, INT, NONE} },
    { "getcpu", INT, (int[]){POINTER, POINTER, POINTER, NONE} },
    { "process_vm_readv", LONG,
        (int[]){INT, POINTER, SIZE_T, POINTER, SIZE_T, SIZE_T, NONE} },
    { "process_vm_writev", LONG,
        (int[]){INT, POINTER, SIZE_T, POINTER, SIZE_T, SIZE_T, NONE} },
    { "kcmp", INT, (int[]){INT, INT, INT, SIZE_T, SIZE_T, NONE} },
    { "finit_module", INT, (int[]){INT, STRING, INT, NONE} },
    { "sched_setattr", INT, (int[]){INT, POINTER, UNSIGNED, NONE} },
    { "sched_getattr", INT, (int[]){INT, POINTER, UNSIGNED, UNSIGNED, NONE} },
    { "renameat2", INT, (int[]){INT, STRING, INT, STRING, UNSIGNED, NONE} },
    { "seccomp", INT, (int[]){UNSIGNED, UNSIGNED, POINTER, NONE} },
    { "getrandom", LONG, (int[]){POINTER, SIZE_T, UNSIGNED, NONE} },
    { "memfd_create", INT, (int[]){STRING, UNSIGNED, NONE} },
    { "kexec_file_load", LONG,
        (int[]){INT, INT, SIZE_T, STRING, SIZE_T, NONE} },
    { "bpf", INT, (int[]){INT, POINTER, UNSIGNED, NONE} },
    { "execveat", INT, (int[]){INT, STRING, POINTER, POINTER, INT, NONE} },
    { "userfaultfd", INT, (int[]){INT, NONE} },
    { "membarrier", INT, (int[]){INT, INT, NONE} },
    { "mlock2", INT, (int[]){POINTER, SIZE_T, INT, NONE} },
    { "copy_file_range", LONG,
        (int[]){INT, POINTER, INT, POINTER, SIZE_T, UNSIGNED, NONE} },
    { "preadv2", LONG, (int[]){INT, POINTER, INT, LONG, INT, NONE} },
    { "pwritev2", LONG, (int[]){INT, POINTER, INT, LONG, INT, NONE} },
    { "pkey_mprotect", INT, (int[]){POINTER, SIZE_T, INT, INT, NONE} },
    { "pkey_alloc", INT, (int[]){SIZE_T, SIZE_T, NONE} },
    { "pkey_free", INT, (int[]){INT, NONE} },
    { "statx", INT, (int[]){INT, STRING, INT, UNSIGNED, POINTER, NONE} }
};