##
## EPITECH PROJECT, 2020
## MAT_302separation
## File description:
## Makefile
##

NAME	=	302separation

SRC		=	302separation.lua

all:
	cp $(SRC) $(NAME)
	chmod +x $(NAME)

clean:

fclean:
	rm -f $(NAME)

re: fclean all